### ISSUE TITLE
Native crash when reordering Unity 2023.1.4f

### ISSUE THREAD

**Issue by SwingWren** [AlexeyTaranov/SerializeReferenceDropdown#17] opened 2023-07-19 06:52 UTC
I'm getting  a native crash while reordering elements that have children that use the `SerializeReferenceDropdown` attribute.

![image](https://github.com/AlexeyTaranov/SerializeReferenceDropdown/assets/54956736/d4582b27-dea6-4ab9-9e1f-37a855552c1b)

I'll try to dig a bit deeper to try to find the issue

`         at <unknown> <0xffffffff>
	  at UnityEditor.SerializedProperty:MoveArrayElementInternal <0x0009e>
	  at UnityEditor.SerializedProperty:MoveArrayElement <0x000f2>
	  at UnityEditorInternal.ReorderableList:DoDraggingAndSelection <0x021ca>
	  at UnityEditorInternal.ReorderableList:DoListElements <0x02a6a>
	  at UnityEditorInternal.ReorderableList:DoList <0x007d2>
	  at UnityEditorInternal.ReorderableListWrapper:DrawChildren <0x00b32>
	  at UnityEditorInternal.ReorderableListWrapper:Draw <0x013ca>
	  at UnityEditor.PropertyHandler:OnGUI <0x0136a>
	  at UnityEditor.PropertyHandler:OnGUI <0x0013a>
	  at UnityEditor.PropertyHandler:OnGUI <0x01baa>
	  at UnityEditor.PropertyHandler:OnGUI <0x0013a>
	  at Defaults:DrawElement <0x002c2>
	  at UnityEditorInternal.ReorderableList:DoListElements <0x0265a>
	  at UnityEditorInternal.ReorderableList:DoList <0x007d2>
	  at UnityEditorInternal.ReorderableListWrapper:DrawChildren <0x00b32>
	  at UnityEditorInternal.ReorderableListWrapper:Draw <0x013ca>
	  at UnityEditor.PropertyHandler:OnGUI <0x0136a>
	  at UnityEditor.PropertyHandler:OnGUI <0x0013a>
	  at UnityEditor.PropertyHandler:OnGUILayout <0x001a2>
	  at UnityEditor.EditorGUILayout:PropertyField <0x00052>
	  at UnityEditor.EditorGUILayout:PropertyField <0x00032>
	  at MyBox.Internal.FoldoutAttributeHandler:Body <0x0019a>
	  at MyBox.Internal.FoldoutAttributeHandler:OnInspectorGUI <0x00032>
	  at MyBox.Internal.UnityObjectEditor:OnInspectorGUI <0x000ca>
	  at <>c__DisplayClass72_0:<CreateInspectorElementUsingIMGUI>b__0 <0x0099b>
	  at UnityEngine.UIElements.IMGUIContainer:DoOnGUI <0x00a1e>
	  at UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent <0x0040a>
	  at UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent <0x0014a>
	  at UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent <0x00032>
	  at UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUIRaw <0x000ba>
	  at UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUI <0x005b2>
	  at UnityEngine.UIElements.IMGUIContainer:ProcessEvent <0x00052>
	  at UnityEngine.UIElements.IMGUIContainer:ExecuteDefaultActionAtTarget <0x0005a>
	  at UnityEngine.UIElements.EventDispatchUtilities:HandleEvent_DefaultActionAtTarget <0x000f0>
	  at UnityEngine.UIElements.EventDispatchUtilities:DispatchToCapturingElement <0x003ca>
	  at UnityEngine.UIElements.EventDispatchUtilities:DispatchToCapturingElementOrElementUnderPointer <0x00032>
	  at UnityEngine.UIElements.MouseEventBase`1:Dispatch <0x00042>
	  at UnityEngine.UIElements.EventDispatcher:ProcessEvent <0x000e6>
	  at UnityEngine.UIElements.EventDispatcher:ProcessEventQueue <0x00162>
	  at UnityEngine.UIElements.EventDispatcher:OpenGate <0x00072>
	  at UnityEngine.UIElements.EventDispatcherGate:Dispose <0x0002a>
	  at UnityEngine.UIElements.EventDispatcher:ProcessEvent <0x001e2>
	  at UnityEngine.UIElements.EventDispatcher:Dispatch <0x00112>
	  at UnityEngine.UIElements.BaseVisualElementPanel:SendEvent <0x0007a>
	  at UnityEngine.UIElements.UIElementsUtility:DoDispatch <0x0054a>
	  at UnityEngine.UIElements.UIElementsUtility:UnityEngine.UIElements.IUIElementsUtility.ProcessEvent <0x000f2>
	  at UnityEngine.UIElements.UIEventRegistration:ProcessEvent <0x0008e>
	  at <>c:<.cctor>b__1_2 <0x0002a>
	  at UnityEngine.GUIUtility:ProcessEvent <0x000f2>
	  at <Module>:runtime_invoke_void_int_intptr_intptr& <0x00095>`

**Comment by AlexeyTaranov** [comment] 2023-07-19 11:44
@SwingWren Can you add some samples in UnityPackage?

**Comment by AlexeyTaranov** [comment] 2023-07-19 18:20
@SwingWren Its unity editor problem. I can't reproduce this bug on unity 2022 version.
U can simplify your data or downgrade to previous versions.

Unity 2022 
<img width="1691" alt="Screenshot 2023-07-19 at 22 06 48" src="https://github.com/AlexeyTaranov/SerializeReferenceDropdown/assets/19202210/c283f8ee-21f2-4d16-a9b0-5b43ddee28c6">

Unity 2023
<img width="1675" alt="Screenshot 2023-07-19 at 22 07 40" src="https://github.com/AlexeyTaranov/SerializeReferenceDropdown/assets/19202210/393eaf41-e794-4d0c-8577-281cc85218f0">

Will wait response from unity support. https://unity3d.atlassian.net/servicedesk/customer/portal/2/IN-48404

**Comment by AlexeyTaranov** [comment] 2024-03-21 14:10
https://unity3d.atlassian.net/servicedesk/customer/portal/2/IN-48404
Looks like, all fixed in new versions.

<details>
<summary>From link</summary>
All fixes for this bug report have been resolved and closed.

Summary:

Branch:2023.1.X
Resolution: Won't Fix
Resolution Notes: 

Branch:2023.2.X
Resolution: Fixed
Fix Versions: 2023.2.0b18
Resolution Notes: 

Branch:2022.3.X
Resolution: Fixed
Fix Versions: 2022.3.13f1
Resolution Notes: 

Branch:2023.3.X
Resolution: Fixed
Fix Versions: 2023.3.0a12
Resolution Notes: 

</details>

**Closed by AlexeyTaranov** 2024-03-21 14:10 UTC
